### ISSUE TITLE
got error when opening frontend

### ISSUE THREAD

**Issue by teamplayer3** [realAP/myfinance#9]
I tried to connect to `localhost:8080` and got the following error:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Feb 21 08:38:16 GMT 2024
There was an unexpected error (type=Not Found, status=404).
```

Maybe you can add an entry in README how to open the frontend?

**Comment by realAP** [comment]
Hi, thanks for the feedback.

open localhost:8080/overview

**Comment by realAP** [comment]
redirect /overview to /

**Comment by realAP** [comment]
done with switch to angular
